export const FETCH_CATEGORY = "FETCH_CATEGORY";
export const CREATE_CATEGORY = "CREATE_CATEGORY";

export const FETCH_INGREDIENT = "FETCH_INGREDIENT";
export const CREATE_INGREDIENT = "CREATE_INGREDIENT";
